name: Flutter Docker Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable"

      - name: Build Docker image
        run: |
          docker build -t flutter-app .

      - name: Run build in container
        run: |
          docker run --rm -v $(pwd)/build:/app/build flutter-app

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apk
          path: build/app/outputs/
          retention-days: 30
