name: Flutter Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      run: |
        git clone https://github.com/flutter/flutter.git -b stable --depth 1 /opt/flutter
        echo "/opt/flutter/bin" >> $GITHUB_PATH
        
    - name: Get dependencies
      run: flutter pub get
      
    - name: Build single APK (without split)
      run: flutter build apk --release
      
    - name: Upload single APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: build/app/outputs/flutter-apk/app-release.apk
        retention-days: 30