name: Flutter Docker Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Docker
        run: |
          docker build -t flutter-app .
          docker run --rm -v $(pwd)/output:/app/build/app/outputs flutter-app

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apk
          path: output/
          retention-days: 30
